apiVersion: v1
kind: Pod
metadata:
  name: taskman
  labels:
    app: taskman
spec:
  containers:
  - name: taskman
    image: modularniurad/taskman
    imagePullPolicy: Never
    env:
    - name: DATABASE_URL
      value: postgres://gandalf:hovno@postgre-service/gis
    - name: HOST
      value: 0.0.0.0